name: Django CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Test
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            cd /var/www/velik
            git pull origin main
            source djangovenv/bin/activate
            pip install -r requirements.txt
            systemctl restart apache2
